config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :products
    resources :stockists
    resources :collections
    resources :favorites
    post '/login'       => 'sessions#create'
    get '/logout'       => 'sessions#destroy'
    get '/instagram'   => 'instagram#index'
    get '/currentuser' => 'users#currentuser'
  end

  namespace :admin do
    resources :users
    resources :products
    resources :stockists, except: :show
    resources :collections
    get '/favorites' => 'favorites#index'
    root 'pages#index'
  end
  
  root 'home#index'

  get '/login'        => 'sessions#new', as: 'login'
  post '/login'       => 'sessions#create'
  get '/logout'       => 'sessions#destroy', as: 'logout'

end

app/models/stockist.rb
class Stockist < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/stockists_controller.rb
module Admin
  class StockistsController < ApplicationController
    before_action :require_admin

    def index
      @stockists = Stockist.all
    end

    def new
      @stockist = Stockist.new
    end

    def create
      @stockist = Stockist.new(stockist_params)
      if @stockist.valid?
        if @stockist.save
          redirect_to admin_stockists_path
        end
      else
        render :new
      end
    end

    def edit
      @stockist = Stockist.find(params[:id])
    end

    def update
      @stockist = Stockist.find(params[:id])
      if @stockist.update(stockist_params)
        redirect_to admin_stockists_path
      else
        render :edit
      end
    end

    def destroy
      @stockist = Stockist.find(params[:id])
      # Need to add confirm dialog in markup: http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html
      @stockist.destroy
      redirect_to admin_stockists_path
    end


    private

    def stockist_params
      params.require(:stockist).permit(:name, :url)
    end

  end
end

app/controllers/api/stockists_controller.rb
module Api
  class StockistsController < ApplicationController
    protect_from_forgery with: :null_session

    def index
      stockists = Stockist.all
      render json: stockists
    end

    private

    def stockist_params
      params.require(:stockist).permit(:name, :url)
    end

  end

end

app/controllers/stockists_controller.rb
class StockistsController < ApplicationController

  before_action :require_admin, except: :index

  def index
    @stockists = Stockist.all
  end

  def new
    @stockist = Stockist.new
  end

  def create
    @stockist = Stockist.new(stockist_params)
    if @stockist.valid?
      if @stockist.save
        redirect_to stockists_path
      end
    else
      render :new
    end
  end

  def edit
    @stockist = Stockist.find(params[:id])
  end

  def update
    @stockist = Stockist.find(params[:id])
    if @stockist.update(stockist_params)
      redirect_to stockists_path
    else
      render :edit
    end
  end

  def destroy
    @stockist = Stockist.find(params[:id])
    # Need to add confirm dialog in markup: http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html
    @stockist.destroy
    redirect_to stockists_path
  end


  private

  def stockist_params
    params.require(:stockist).permit(:name, :url)
  end

end

app/views/admin/stockists/_form.html.erb
<%= form_for ([:admin, @stockist]) do |f| %>
	<%= f.text_field :name, placeholder: 'Name' %>
	<%= f.text_field :url, placeholder: 'URL' %>
	<%= f.submit %>
<% end %>

app/views/admin/stockists/edit.html.erb
<%= render 'adminheader' %>

<div class="admin-container">
  <h2>Edit Stockist</h2>
  <%= render 'form' %>
</div>

app/views/admin/stockists/index.html.erb
<%= render 'adminheader' %>


<div class="admin-container">
  <h2>Stockists</h2>
  <%= link_to "Add New", new_admin_stockist_path %>
  <% @stockists.each do |stockist| %>
  	<h3><%= stockist.name %></h3>
  		<%= link_to "Edit", edit_admin_stockist_path(stockist.id) %> | <%= link_to 'Delete', { 
  				action: "destroy", id: stockist.id }, method: :delete, data: { confirm: "Are you sure?" } %>
  	<p><%= link_to stockist.url, "http://#{stockist.url}", target: '_blank' %></p>
  	<br>
  <% end %>
</div>

app/views/admin/stockists/new.html.erb
<%= render 'adminheader' %>


<div class="admin-container">
  <h2>Add a new Stockist</h2>
  <%= render 'form' %>
</div>