config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :products
    resources :stockists
    resources :collections
    resources :favorites
    post '/login'       => 'sessions#create'
    get '/logout'       => 'sessions#destroy'
    get '/instagram'   => 'instagram#index'
    get '/currentuser' => 'users#currentuser'
  end

  namespace :admin do
    resources :users
    resources :products
    resources :stockists, except: :show
    resources :collections
    get '/favorites' => 'favorites#index'
    root 'pages#index'
  end
  
  root 'home#index'

  get '/login'        => 'sessions#new', as: 'login'
  post '/login'       => 'sessions#create'
  get '/logout'       => 'sessions#destroy', as: 'logout'

end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::SecurePassword
  has_secure_password
  has_many :favorites

  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :password_confirmation, presence: true
  validates :company, presence: true

  def fullname
    "#{first_name} #{last_name}"
  end

  def is_admin?
    self.admin == true
  end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :require_admin

    def index
      @users = User.all
    end
    
    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.valid?
        if @user.save
          flash[:info] = "#{@user.fullname} added as new User"
          redirect_to admin_users_path
        end
      else
        # Need to add flash message if user is missing fields
        flash[:error] = "This user has already been registered."
        render :new
      end
    end

    def show
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to admin_users_path
      else
        render :edit
      end
    end

    def destroy
      @user = User.find(params[:id])
      # Need to add confirm dialog in markup: http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html
      @user.destroy
      redirect_to admin_users_path
    end


    private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :company, :password, :password_confirmation)
    end

  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController

    def currentuser
      render json: (current_user ? current_user : false), except: :password_digest, include: :favorites
    end

  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<%=	f.text_field :first_name, placeholder: 'First Name' %>
	<%= f.text_field :last_name, placeholder: 'Last Name' %>
	<%= f.text_field :email, placeholder: 'Email' %>
	<%= f.text_field :company, placeholder: 'Company' %>
	<%= f.password_field :password, placeholder: 'Password' %>
	<%= f.password_field :password_confirmation, placeholder: 'Confirm Password' %>
	<%= f.submit 'Add New' %>
<% end %>

app/views/users/index.html.erb
<h2>List of Users</h2>
<p><%= flash[:info] %></p>
<%= link_to "Add New", new_user_path %>
<% @users.each do |user| %>
	<h3><%= link_to user.fullname, user_path(user.id) %></h3>	
	<p><%= user.company %></p>
	<p><%= mail_to user.email %></p>
	<br>
<% end %>