config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :products
    resources :stockists
    resources :collections
    resources :favorites
    post '/login'       => 'sessions#create'
    get '/logout'       => 'sessions#destroy'
    get '/instagram'   => 'instagram#index'
    get '/currentuser' => 'users#currentuser'
  end

  namespace :admin do
    resources :users
    resources :products
    resources :stockists, except: :show
    resources :collections
    get '/favorites' => 'favorites#index'
    root 'pages#index'
  end
  
  root 'home#index'

  get '/login'        => 'sessions#new', as: 'login'
  post '/login'       => 'sessions#create'
  get '/logout'       => 'sessions#destroy', as: 'logout'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :products
  validates :name, uniqueness: true
end

app/controllers/admin/collections_controller.rb
module Admin
  class CollectionsController < ApplicationController
    before_action :require_admin
    
    def index
      @collections = Collection.all
    end

    def new
      @collection = Collection.new
    end

    def create
      @collection = Collection.new(require(:collection).permit(:name))
      if @collection.save
        redirect_to admin_collection_path
      else
        render :new
      end
    end

  end
end

app/controllers/api/collections_controller.rb
module Api
  class CollectionsController < ApplicationController
    protect_from_forgery with: :null_session

    def current
      collection = Collection.find_by(current: true)
      products = Product.where(collection_id: collection.id)
      render json: products
    end

  end
end

app/views/admin/collections/index.html.erb
<%= render 'adminheader' %>

<div class="admin-container">
  <h2>Collections</h2>
  <% @collections.each do |c| %>
  	<p><%= c.name %></p>
  <% end %>
  <%= link_to 'Add New Collection', new_admin_collection_path %>
</div>

app/views/admin/collections/new.html.erb
<%= render 'adminheader' %>

<div class="admin-container">
  <h2>Add New Collection</h2>
  <%= form_for ([:admin, @collection]) do |f| %>
  	<%= f.select :name, [['Fall 2016'],['Winter 2016'],['Spring 2017'],['Summer 2017'],['Fall 2017']] %>
  	<%= f.submit %>
  <% end %>
</div>