config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :products
    resources :stockists
    resources :collections
    resources :favorites
    post '/login'       => 'sessions#create'
    get '/logout'       => 'sessions#destroy'
    get '/instagram'   => 'instagram#index'
    get '/currentuser' => 'users#currentuser'
  end

  namespace :admin do
    resources :users
    resources :products
    resources :stockists, except: :show
    resources :collections
    get '/favorites' => 'favorites#index'
    root 'pages#index'
  end
  
  root 'home#index'

  get '/login'        => 'sessions#new', as: 'login'
  post '/login'       => 'sessions#create'
  get '/logout'       => 'sessions#destroy', as: 'logout'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :collection
  has_many :favorites
  has_many :favorited_users, through: :favorites, source: :user
  has_many :images
  accepts_nested_attributes_for :images
  validates :style_num, presence: true, uniqueness: true
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < ApplicationController
    before_action :require_admin

    def index
      @products = Product.all
    end

    def new
      @product = Product.new
      # Builds three image inputs on new product page
      3.times do
        @product.images.build
      end
    end

    def create
      @product = Product.new(product_params)
      if @product.valid?
        if @product.save
          redirect_to admin_products_path
        end
      else
        render :new
      end
    end

    def show
      @product = Product.find(params[:id])
    end

    def edit
      @product = Product.find(params[:id])
    end

    def update
      @product = Product.find(params[:id])
      if @product.update(product_params)
        redirect_to admin_products_path
      else
        render :edit
      end
    end

    def destroy
      @product = Product.find(params[:id])
      # Need to add confirm dialog in markup: http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html
      @product.destroy
      redirect_to admin_products_path
    end


    private

    def product_params
      params.require(:product).permit(:collection_id, :category, :style_num, :style, :color, :materials, :description, images_attributes: [:id, :source, :description])
    end


  end
end

app/controllers/api/products_controller.rb
module Api
  class ProductsController < ApplicationController
    protect_from_forgery with: :null_session

    def index
      results = params[:results].to_i;
      start = params[:start].to_i;
      if results > 0
        products = Product.limit(results).offset(start)
      else
        products = Product.all
      end
      render json: products
      # if current_user
      #   favorites = current_user.favorites.includes(:product)
      #   render json: favorites, include: :product
      # else
      #   render json: {}
      # end
    end

    def show
      product = Product.find(params[:id])
      # favorited_users = product.favorited_users
      render json: product
    end

    private

      def product_params
        params.require(:product).permit(:collection_id, :category, :style_num, :style, :color, :materials, :description, images_attributes: [:id, :source, :description])
      end

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :require_admin, except: [:index, :show]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    # Builds three image inputs on new product page
    3.times do
      @product.images.build
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.valid?
      if @product.save
        redirect_to products_path
      end
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
    @product.images.build
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    # Need to add confirm dialog in markup: http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html
    @product.destroy
    redirect_to products_path
  end


  private

  def product_params
    params.require(:product).permit(:collection_id, :category, :style_num, :style, :color, :materials, :description, images_attributes: [:id, :source, :description])
  end

end

app/views/admin/products/_form.html.erb
<div class="form-container">
	<%= form_for ([:admin, @product]) do |f| %>
		Collection: <%= f.collection_select(:collection_id, Collection.all, :id, :name )%>
		<br>
		Category: <%= f.select :category, [['Tops'],['Pants'],['Skirts'],['Dresses'],['Jumpsuits'],['Jackets']] %>
		<%#= f.text_field :style, placeholder: 'Style' %>
		<%= f.text_field :style_num, placeholder: 'Style #' %>
		<%#= f.text_field :color, placeholder: 'Color' %>
		<%= f.text_field :materials, placeholder: 'Materials' %>
		<%= f.text_field :description, placeholder: 'Description' %>
		<br>
		<p>Image Uploads</p>
		<%= f.fields_for :images do |image| %>
			<%= image.file_field :source %>
			<%= image.select :description, [['front'], ['side'], ['back']] %>
			<br><br>	
		<% end %>
		<%= f.submit 'Submit' %>
	<% end %>
</div>

app/views/admin/products/edit.html.erb
<%= render 'adminheader' %>

<div class="admin-container">
  <h2>Edit Product</h2>
  <%= render 'form' %>
</div>

app/views/admin/products/index.html.erb
<%= render 'adminheader' %>

<div class="admin-container">
  <h2>Products</h2>
  <button><%= link_to "Add New", {action: "new" }, method: :get %></button>
  <br>
  <br>
  <section class="products">
    <% @products.each do |product| %>
    	<div class="product">
    		<%= image_tag product.images.first.source.thumb %>
    		<p><%= link_to product.style_num, admin_product_path(product.id) %></p>
    	</div>
    <% end %>
  </section>
</div>

app/views/admin/products/new.html.erb
<%= render 'adminheader' %>

<div class="admin-container">
  <h2>Create product</h2>
  <%= render 'form' %>
</div>

app/views/admin/products/show.html.erb
<%= render 'adminheader' %>

<div class="admin-container">
	<div>
		<h2><%= @product.style %></h2>
		<% if current_user %>
			<% if current_user.is_admin? %>
				<p><%= link_to 'Edit', edit_admin_product_path %> | <%= link_to 'Delete', { 
					action: "destroy", id: @product.id }, method: :delete, data: { confirm: "Are you sure?" } %></p>		
			<% end %>
		<% end %>

		<% if @product.images.empty? == false %>
			<%= image_tag @product.images.first.source.medium %>
		<% end %>
		<p><%=  @product.category %></p>
		<p><%=  @product.style_num %></p>
		<p><%=  @product.color %></p>
		<p><%=  @product.description %></p>

		<%= link_to 'Back to Collection', admin_products_path %>
	</div>
</div>